name: Release PicoRVD
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PicoRVD
        uses: actions/checkout@v5
        with:
          path: PicoRVD

      - name: Checkout pico-sdk/master
        uses: actions/checkout@v5
        with:
          repository: raspberrypi/pico-sdk
          ref: master
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/pico-sdk
        run: git submodule update --init

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential git cmake gcc-arm-none-eabi gcc-riscv64-unknown-elf

      - name: Build Project (PicoRVD)
        working-directory: ${{github.workspace}}/PicoRVD
        # bash required otherwise this mysteriously (no error) fails at "Generating cyw43_bus_pio_spi.pio.h"
        shell: bash
        run: |
          mkdir bin
          INCLUDE_BIN=ON
          if [ "$RUNNER_OS" == "Windows" ]; then
              INCLUDE_BIN=OFF
          fi
          cmake -B bin -G "Unix Makefiles" -DPICO_SDK_PATH=../pico-sdk -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DINCLUDE_BLINKY_BINARY:BOOL=$INCLUDE_BIN -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico
          make -j8 -C bin

      - name: Upload UF2 File
        uses: actions/upload-artifact@v5
        with:
          name: PicoRVD.uf2
          path: ${{github.workspace}}/PicoRVD/bin/picorvd.uf2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: ${{ github.workspace }}/PicoRVD/bin/picorvd.uf2
